Fixing gcc error on installation
When installing with the current release, I get the following gcc error:

```
c_src/common.h: In function ‘calc_limb_darkening’:
c_src/common.h:559:40: error: expected identifier or ‘(’ before ‘__extension__’
  559 |                                 double I = intensity(x - dx/2., intensity_args);        //intensity at the midpoint
      |                                        ^
c_src/common.h:574:32: error: expected identifier or ‘(’ before ‘__extension__’
  574 |                         double I = intensity(x - dx/2., intensity_args);                //intensity at the midpoint
      |                                ^
```

It turned out that just renaming the variable `I` to anything else resolved the issue and let me install the package